# * Copyright 2025 Lukas Spies <Lukas@previewqt.org>
# * SPDX-License-Identifier: GPL-2.0-or-later
name: previewqt
confinement: strict
grade: stable
base: core22
architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

adopt-info: previewqt

description: Very fast and simple file previewer with a clean interface, supporting a very large number of all kinds of files, including images, videos, and documents.
summary: Simple and fast application for previewing all kinds of files.

contact: Lukas@previewqt.org
issues: https://gitlab.com/lspies/previewqt/-/issues
source-code: https://gitlab.com/lspies/previewqt
website: https://previewqt.org
donation: https://previewqt.org/donate

apps:
  previewqt:
    extensions:
      - kde-neon-6
    common-id: org.previewqt.PreviewQt
    desktop: usr/local/share/applications/org.previewqt.PreviewQt.desktop
    command: usr/local/bin/previewqt
    slots:
      - session-slot
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - unity7
      - audio-playback
      - network
      - network-bind
      - cups
      - session-plug

compression: lzo

plugs:
  session-plug:
    interface: dbus
    bus: session
    name: org.previewqt.PreviewQt
    
slots:
  session-slot:
    interface: dbus
    bus: session
    name: org.previewqt.PreviewQt

parts:
  previewqt:
    plugin: cmake
    source: https://previewqt.org/downloads/source/previewqt-3.0.tar.gz
    parse-info:
      - usr/local/share/metainfo/org.previewqt.PreviewQt.metainfo.xml
    override-build: |
      ln -sf /usr/include/GraphicsMagick/Magick++ /usr/include/Magick++
      ln -sf /usr/include/GraphicsMagick/magick /usr/include/magick
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DRAW=ON
      - -DIMAGEMAGICK=OFF
      - -DGRAPHICSMAGICK=ON
      - -DDEVIL=ON
      - -DFREEIMAGE=ON
      - -DPOPPLER=OFF
      - -DQTPDF=ON
      - -DLIBARCHIVE=ON
      - -DVIDEO_QT=ON
      - -DVIDEO_MPV=ON
      - -DEXIV2=ON
      - -DPUGIXML=ON
      - -DMOTIONPHOTO=ON
      - -DPHOTOSPHERE=ON
      - -DLCMS2=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libdevil-dev
      - libfreeimageplus-dev
      - libarchive-dev
      - libmpv-dev
      - libgraphicsmagick++1-dev
      - libgraphicsmagick1-dev
      - libcups2-dev
    stage-packages:
      - libheif1
      - libjpeg8
      - libjpeg-turbo8
      - libx265-199
      - libgif7
      - kimageformat-plugins
      - libraw20
      - ghostscript
      - libdevil1c2
      - libfreeimage3
      - libarchive13
      - libmpv1
      - libjxr0
      - libdjvulibre21
      - libgraphicsmagick-q16-3
      - libgraphicsmagick++-q16-12
      - graphicsmagick
      - libcups2
