# * Copyright 2025 Lukas Spies <Lukas@previewqt.org>
# * SPDX-License-Identifier: GPL-2.0-or-later
name: previewqt
confinement: strict
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

adopt-info: previewqt

description: Very fast and simple file previewer with a clean interface, supporting a very large number of all kinds of files, including images, videos, and documents.
summary: Simple and fast application for previewing all kinds of files.

contact: Lukas@previewqt.org
issues: https://gitlab.com/lspies/previewqt/-/issues
source-code: https://gitlab.com/lspies/previewqt
website: https://previewqt.org
donation: https://previewqt.org/donate

apps:
  previewqt:
    extensions:
      - kde-neon-6
    common-id: org.previewqt.PreviewQt
    desktop: usr/local/share/applications/org.previewqt.PreviewQt.desktop
    command: usr/local/bin/previewqt
    slots:
      - session-slot
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - unity7
      - audio-playback
      - network
      - network-bind
      - session-plug
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy"

compression: lzo

plugs:
  session-plug:
    interface: dbus
    bus: session
    name: org.previewqt.PreviewQt

slots:
  session-slot:
    interface: dbus
    bus: session
    name: org.previewqt.PreviewQt

parts:
  previewqt:
    plugin: cmake
    source: https://previewqt.org/downloads/source/previewqt-4.0.tar.gz
    parse-info:
      - usr/local/share/metainfo/org.previewqt.PreviewQt.metainfo.xml
    override-build: |
      ln -sf /usr/include/GraphicsMagick/Magick++ /usr/include/Magick++
      ln -sf /usr/include/GraphicsMagick/magick /usr/include/magick
      snapcraftctl build
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITH_LIBRAW=ON
      - -DWITH_IMAGEMAGICK=OFF
      - -DWITH_GRAPHICSMAGICK=ON
      - -DWITH_DEVIL=ON
      - -DWITH_FREEIMAGE=ON
      - -DWITH_POPPLER=OFF
      - -DWITH_QTPDF=ON
      - -DWITH_LIBARCHIVE=ON
      - -DWITH_VIDEO_QT=ON
      - -DWITH_VIDEO_MPV=ON
      - -DWITH_EXIV2=ON
      - -DWITH_MOTIONPHOTO=ON
      - -DWITH_PHOTOSPHERE=ON
      - -DWITH_LCMS2=ON
      - -DWITH_EPUB=ON
    build-packages:
      - libexiv2-dev
      - libexpat1-dev
      - libheif-dev
      - libjpeg-dev
      - liblcms2-dev
      - libpng-dev
      - libtiff-dev
      - libxml2-dev
      - libraw-dev
      - libdevil-dev
      - libfreeimageplus-dev
      - libarchive-dev
      - libmpv-dev
      - libgraphicsmagick++1-dev
      - libgraphicsmagick1-dev
      - libproxy1v5
    stage-packages:
      - libheif1
      - libjpeg8
      - libjpeg-turbo8
      - libx265-199
      - libgif7
      - kimageformat-plugins
      - libraw23t64
      - ghostscript
      - libdevil1c2
      - libfreeimage3
      - libarchive13t64
      - libmpv2
      - libjxr0t64
      - libdjvulibre21
      - libgraphicsmagick-q16-3t64
      - libgraphicsmagick++-q16-12t64
      - graphicsmagick
      - gsettings-desktop-schemas
